In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, GaussianNB
!pip install streamlit
import streamlit as st

Requirement already satisfied: streamlit in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.54.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.4.2)
Requirement already satisfied: packaging>=20 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (12.1.1)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.33.5)
Requirement already satisfied: pyarrow>=7.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.5.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.27.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.17.0)
Requirement already satisfied: colorama in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in C:\Users\Wlecome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
df.drop(columns=['Category'],inplace=True)
df.head()

                                             Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
x_train,x_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=.3,random_state=34)

v = CountVectorizer()
X_train_count = v.fit_transform(x_train)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3900, 7184))

In [8]:
model=MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [9]:
x_test_count = v.transform(x_test)
model.score(x_test_count,y_test)

0.9892344497607656

In [10]:
from sklearn.metrics import accuracy_score, precision_score , recall_score,f1_score,confusion_matrix
y_pred=model.predict(x_test_count)
print("Accuracy : ", accuracy_score(y_test,y_pred))
print("Precision : ", precision_score(y_test,y_pred))
print("Recall : ", recall_score(y_test,y_pred))
print("F1- score : ",f1_score(y_test,y_pred))
print("\n" ,confusion_matrix(y_test,y_pred))

Accuracy :  0.9892344497607656
Precision :  0.9905660377358491
Recall :  0.9292035398230089
F1- score :  0.958904109589041

 [[1444    2]
 [  16  210]]

In [11]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'i have offer for you 1000 rupees off and free travel,hurry up!!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1, 1])

In [12]:
import joblib

In [13]:
final='model.sav'
joblib.dump(model,open(final,'wb'))

joblib.dump(v,open('vectorizer.pkl','wb'))